### PR TITLE
Fix the semi donut 6a display with the overlapping text

### LINKED ISSUE #34: Fix the semi-donut 6a display with the overlapping text

### PR DESCRIPTION
**Pull request by ziyue5**
resolves #34

### CODE REVIEW

**Comment by navarroc** [comment]
Ziyue, can you fix the extraneous comma in the text above the semi-donut chart. On line 159, you can see:

"treating agricultural wastes, ;"

There shouldn't be a comma before the semi-colon

**Comment by navarroc** [comment]
This change looks good besides the one remark to fix the text issue.

**Comment by ziyue5** [comment]
> Ziyue, can you fix the extraneous comma in the text above the semi-donut chart. On line 159, you can see:
> 
> "treating agricultural wastes, ;"
> 
> There shouldn't be a comma before the semi-colon

Fixed

**Review by navarroc — APPROVED** [review]

**Comment by sandeep-ps** [comment]
6(A) practices percentages don't seem to add up to 100. Please check this.

**Review by sandeep-ps — APPROVED** [review]
The updates look good. Approving.

**Pull request merged**
