### PR TITLE
SNAP Page with Colored Navbar

### PR DESCRIPTION
**Pull request by pengyin-shan**
This PR includes:

1. The SNAP Page with a bar and table [#59] has been approved by Johnathan. I have updated the 'Explore SNAP Map' button on the landing page to allow users to navigate to the SNAP page and return to the landing page by clicking the PDL logo.

2. I have added parameters to the NavBar to enable switching between light and dark themes. However, I have not updated EQIP in case it affects any ongoing changes. Once this PR is approved, we can apply the light NavBar to other sub-pages, including EQIP, to match the design in Figma.

3. I have added an unfunctional route bar (including a link and a search icon) as a placeholder. Although we haven't discussed how it will be functionalized, we can incorporate it into all sub-pages to align with the Figma design.

 4. All 'Benefits' for SNAP have been replaced with 'Costs,' including both maps on the landing page and SNAP page, the SNAP bar chart, and the SNAP table. No other maps have been affected.
 
 5. As per Chris's request, I have added a highlight to the state name when the user hovers over the bar chart.
 
 6. I have made indent adjustments to several other pages.

### CODE REVIEW

**Comment by sandeep-ps** [comment]
This PR looks good to me. I see "The map shows the total SNAP benefits of the nutrition title by state from 2018-2022." on the SNAP's main page. You may want to check if that needs to be changed to "The map shows the total SNAP costs of the nutrition title by state from 2018-2022."

**Comment by sandeep-ps** [comment]
I'm seeing this as the navigation bar on the home page: 
image
Are you seeing something similar?

**Comment by pengyin-shan** [comment]
> In general, this PR looks good to me. I see "The map shows the total SNAP benefits of the nutrition title by state from 2018-2022." on the SNAP's main page. You may want to check if that needs to be changed to "The map shows the total SNAP costs of the nutrition title by state from 2018-2022."

good catch! I'll fix that

**Comment by pengyin-shan** [comment]
@sandeep-ps I have fixed the issues you found

**Review by sandeep-ps — APPROVED** [review]
Thanks for fixing the suggestions.

**Review by ziyue5 — APPROVED** [review]
Looks all good to me

**Review by ywkim312 — APPROVED** [review]

**Comment by pengyin-shan** [comment]
Thank you all! I'll merge it to dev

**Pull request merged**
