### PR TITLE
Change number style for semi-donut chart

### LINKED ISSUE #64: Change number style for semi-donut chart

### PR DESCRIPTION
**Pull request by ziyue5**
resolves #64

### CODE REVIEW

**Comment by navarroc** [comment]
This change looks good; however, I wonder if we can detect if the number is less than 1 Billion, display Millions. For example, 6B practices are so small, it's showing $0.04 B. It would in this case be better to display $40 M

**Review by pengyin-shan — APPROVED** [review]
looks good to me

**Comment by pengyin-shan** [comment]
> In the design docs, there is also a recommendation to make the font bold and larger to make it more prominent. Please let me know if that's planned as a different task. Thanks.

Hi @sandeep-ps , can you point to me the design docs? I also want to read it...I currently have access to Figma board and our box folder.

**Comment by ziyue5** [comment]
> This change looks good; however, I wonder if we can detect if the number is less than 1 Billion, display Millions. For example, 6B practices are so small, it's showing $0.04 B. It would in this case be better to display $40 M

Thanks for the suggestion. Fixed it.

**Comment by ziyue5** [comment]
> In the design docs, there is also a recommendation to make the font bold and larger to make it more prominent. Please let me know if that's planned as a different task. Thanks.

Nice catch! Fixed it

**Comment by sandeep-ps** [comment]
> > In the design docs, there is also a recommendation to make the font bold and larger to make it more prominent. Please let me know if that's planned as a different task. Thanks.
> 
> Hi @sandeep-ps , can you point to me the design docs? I also want to read it...I currently have access to Figma board and our box folder.

Hi, Wendy, When I wrote design docs, I was referring to the Figma board (specifically the section titled "EQIP Design+Dev alignment").

**Review by sandeep-ps — APPROVED** [review]

**Comment by sandeep-ps** [comment]
Merging this PR.

**Pull request merged**
