### PR TITLE
[0.11.0 Release] DMC & SADA page, Logo Change, Webpack Building Update

### PR DESCRIPTION
**Pull request by pengyin-shan**
This PR includes #206,#209,#203 .  User has approved the result on dev site.

### CODE REVIEW

**Review by navarroc — APPROVED** [review]

**Comment by sandeep-ps** [comment]
Though not directly related to this PR, one minor thing needs to be updated. The main map title probably needs to be updated to "Total Commodities Programs, Subtitle A", since the left menu tab states so. 
image Please let me know your thoughts. The rest looks good to me. Thanks.

**Comment by navarroc** [comment]
It has been that way since last release, while not disagreeing with you, I'm ok if we want to address this later in another release in case the title length causes any display issues. We should open an issue to address this among other things that need to be tightened up that we discussed before (e.g. there should be a side menu that shows the same map as the landing page for Title I).

**Comment by pengyin-shan** [comment]
> Though not directly related to this PR, one minor thing needs to be updated. The main map title probably needs to be updated to "Total Commodities Programs, Subtitle A", since the left menu tab states so. image
> 
> Please let me know your thoughts. The rest looks good to me. Thanks.

This is because while other programs use the program name from API directly as the title of map (for example, `Agriculture Risk Coverage (ARC)` is in API, then it will be used for the program name on map). The total commodities program doesn't have a program name in API, so it needs to be mannualy updated. I just push a new commit for this.

**Comment by pengyin-shan** [comment]
> It has been that way since last release, while not disagreeing with you, I'm ok if we want to address this later in another release in case the title length causes any display issues. We should open an issue to address this among other things that need to be tightened up that we discussed before (e.g. there should be a side menu that shows the same map as the landing page for Title I).

Yes, later once we update the API, 'll replace the title string with the program name variable, so that what we have in API can be directly used as the map title. Currently, I just mannually added 'Subtitle' to the title string.

The length is still managable as it states here:
Screenshot 2023-11-08 at 1 55 48 PM

We can discuss later with client above this for improvement.

**Review by sandeep-ps — APPROVED** [review]
I tested using a tablet screen using the Chrome developer tool. The changes look good. Approving.

**Pull request merged**
