### PR TITLE
EQIP page update to use  API endpoint

### PR DESCRIPTION
**Pull request by ywkim312**
## Description
EQIP page updated to use the data from API endpoint

## How Has This Been Tested?
Run local using env variable set to APP_ENV=development, the check the page from http://localhost:3000/eqip

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by navarroc** [comment]
Any idea why the tests are failing?

**Comment by ywkim312** [comment]
> Any idea why the tests are failing?

I will ask in the channel

**Review by pengyin-shan — APPROVED** [review]
tested locally and worked well. great job!

**Comment by navarroc** [comment]
Can you fix the changelog conflict?

**Comment by ywkim312** [comment]
> Can you fix the changelog conflict?

fixed it

**Comment by ywkim312** [comment]
@navarroc I finally found a reason. It was the api data in dev. The PR itself is good but when you update the api data in dev/prod, you need to update the json files in mounted volume. Since we are using the mounted volume, just updating the docker images in docker-compose is not enough and we need to sync the json data to the mounted volume as well. I totally forgot about this and it was a good lesson that I probably will not forget about this anymore. There is no changes in the PR but it should have the correct values since I updated the json files in mounted volume in dev instance.

**Review by sandeep-ps — APPROVED** [review]
There is an issue with how pdl-api returns the JSON document (it's somehow sorting the state distribution data by state name). Since, it's not a front-end issue, Yongwook and I discussed it and decided to proceed with this.

**Pull request merged**
