### PR TITLE
Initial landing page and react framework configurations

### PR DESCRIPTION
**Pull request by ziyue5**
The landing page is still static awaiting content and data inputs

### CODE REVIEW

**Comment by navarroc** [comment]
Two suggestions for webpack.dev.js:

1) Add open: true to the devServer section
2) Change port 8080 to 3000 in the devServer since 8080 is a fairly common port that could be in use

**Comment by navarroc** [comment]
Can you also replace the old NCSA logo?

**Comment by navarroc** [comment]
Nevermind about the logo, I see you did that in the other PR. Do you want to make my other suggested changes in your other PR and just merge this?

**Comment by ziyue5** [comment]
Yes, sounds great! I will make the changes in the other PR

**Comment by ziyue5** [comment]
> Nevermind about the logo, I see you did that in the other PR. Do you want to make my other suggested changes in your other PR and just merge this?

Yes, sounds great! I will make the changes in the other PR

**Review by navarroc — APPROVED** [review]

**Comment by ziyue5** [comment]
> Two suggestions for webpack.dev.js:
> 
> 1. Add open: true to the devServer section
> 2. Change port 8080 to 3000 in the devServer since 8080 is a fairly common port that could be in use

Resolved in #4

**Pull request merged**
