### PR TITLE
#317: landing map toggle

### PR DESCRIPTION
**Pull request by pengyin-shan**
This PR addresses issue #317. It introduces the program selection feature to the total map on the landing page. A collaborator has validated the calculated numbers displayed on the map.

## How to Test

1. Navigate to https://policydesignlab-dev.ncsa.illinois.edu/ and review the updated landing page map: Screenshot 2024-10-22 at 9 56 01 AM

2. You should be able to use selectors, and the map’s numbers should change based on your selection. Note that the calculation is dynamic, so the legend bar retains its uniform distribution (i.e., five equal segments), unlike the static legend bars on other landing page maps.

3. Hover your mouse over a state. You should see the full number rather than a rounded figure, ensuring users can view the total more clearly and avoid confusion from rounded values: Screenshot 2024-10-22 at 10 01 59 AM

4. Interact with the map to verify that the calculations are correct.

### CODE REVIEW

**Review by navarroc — APPROVED** [review]

**Comment by navarroc** [comment]
Looks good, did a few different combinations and it looks to function well.

**Comment by navarroc** [comment]
Can you add a changelog entry?

**Comment by pengyin-shan** [comment]
> Can you add a changelog entry?

Yes, I just updated the changelog. Thank you for catching this!

**Review by ywkim312 — APPROVED** [review]
tested in dev site and worked without issue approve

**Pull request merged**
