### PR TITLE
#268: The EQIP IRA page

### PR DESCRIPTION
**Pull request by pengyin-shan**
This PR is for #268 and includes content for the IRA page, with the EQIP section as the first step. You can review it on the dev site: https://policydesignlab-dev.ncsa.illinois.edu/ira. I will mark this release as _1.0_ as we discussed before, but I am open to your thoughts.

Please note that in this PR, I commented out some code while working on the IRA prototype, such as the slider and some min/max prediction calculations. _I want to keep them until the entire IRA page is finished_ so that if collaborators request their re-inclusion, I can easily uncomment these codes instead of recreating the component.

### How to Test

1. Navigate to https://policydesignlab-dev.ncsa.illinois.edu/ira and confirm the model is populated correctly. The model shape could be different depending on your screen shape.

2. Check the map to ensure the data is correctly displayed.

3. Scroll to the bottom of the page to check that the table is correctly displayed, including both the dollar table and the corresponding nationwide percentage table.

4. When you click the "Export this Table to CSV" button, you should be able to download a CSV file named 'pdl-data' for this table:
Screenshot 2024-06-28 at 9 33 27 AM

5. Now navigate to the right side of the page and select random practices instead of Total. You should see the map and tables reflect the updated information. Repeat steps 2 to 4:
Screenshot 2024-06-28 at 9 33 41 AM

6. Select 'Total' from the "Select Practice" list. You should see the total data returned, and all practices cleared out:
Screenshot 2024-06-28 at 9 33 51 AM

7. Now turn the "2024-2031 Prediction" switch on. You should see all data become the predicted data. The map and tables should reflect the changes:
Screenshot 2024-06-28 at 9 34 06 AM

8. Repeat steps 2 to 6 for the predicted data.

### CODE REVIEW

**Comment by navarroc** [comment]
Do we want to make the 1.0 release when we fully switch over to the database?

**Comment by pengyin-shan** [comment]
> Do we want to make the 1.0 release when we fully switch over to the database?
Since the front-end and back-end have different processes, the front-end development at that time may not be appropriate to tag for a major release with no significant changes, while the IRA page could be a better milestone for a major release. However, I am open to this option as well.

**Comment by navarroc** [comment]
> > Do we want to make the 1.0 release when we fully switch over to the database?
> 
> Since the front-end and back-end have different processes, the front-end development at that time may not be appropriate to tag for a major release with no significant changes, while the IRA page could be a better milestone for a major release. However, I am open to this option as well.

I have no strong opinion. Adding in the modeling page for IRA could be a nice milestone for a 1.0 release.

**Comment by pengyin-shan** [comment]
> > > Do we want to make the 1.0 release when we fully switch over to the database?
> > 
> > 
> > Since the front-end and back-end have different processes, the front-end development at that time may not be appropriate to tag for a major release with no significant changes, while the IRA page could be a better milestone for a major release. However, I am open to this option as well.
> 
> I have no strong opinion. Adding in the modeling page for IRA could be a nice milestone for a 1.0 release.

👍 Thanks, Chris. I'll check if there are any other objections to the 1.0 tagging and then consider to move forward with making this the major release.

**Review by navarroc — APPROVED** [review]
Basic testing looks to be all passing. Exported CSV table in both dollars and percents for predicted and actual values for total as well as selecting different practices. Maps seem to be working correctly as well respecting the selected practices and predicted vs actual.

**Comment by navarroc** [comment]
I tested both Chrome and Firefox on Linux

**Review by ywkim312 — APPROVED** [review]
Tested based on the instruction. Approve

**Pull request merged**
