### PR TITLE
170 task create crp page

### PR DESCRIPTION
**Pull request by ywkim312**
## Description
Create CRP frontend page

## How Has This Been Tested?
If you want to test locally, set environment variable like export APP_ENV=development
Then run the package, go to http://localhost:3000/crp
Or this is deployed in dev server
https://policydesignlab-dev.ncsa.illinois.edu/crp

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by pengyin-shan** [comment]
We need a bit of right padding for the last column of the table (on 1920 X 1080, 21" monitor)

Screenshot 2023-09-11 at 9 39 16 AM

**Comment by pengyin-shan** [comment]
Also, just to confirm, we will not add 'As of 2022' as it is in some designs in Figma right? 
Screenshot 2023-09-11 at 11 18 30 AM
Screenshot 2023-09-11 at 11 18 25 AM

**Comment by pengyin-shan** [comment]
> > Also, just to confirm, we will not add 'As of 2022' as it is in some designs in Figma right? Screenshot 2023-09-11 at 11 18 30 AM Screenshot 2023-09-11 at 11 18 25 AM
> 
> Yes I saw that but the other pages doesn't have it. Should I add it?

Ah, I see. It's a good idea to follow one of them since it will be helpful to add the year label for the user. I personally think that the second design would be easier to implement than the first one.

However, you can confirm with Leigh in Slack again in case she has any preferences between these two designs or if she's okay with what's currently in development first.

**Comment by ywkim312** [comment]
> We need a bit of right padding for the last column of the table (on 1920 X 1080, 21" monitor)
> 
> Screenshot 2023-09-11 at 9 39 16 AM

increased the padding values

**Comment by pengyin-shan** [comment]
Good work! just one last thing... the middle column padding seems a bit off after the last column was adjusted (see the 'Grassland')

Screenshot 2023-09-11 at 12 56 53 PM

**Review by navarroc — APPROVED** [review]

**Review by pengyin-shan — APPROVED** [review]

**Pull request merged**
