### PR TITLE
fix issue156

### PR DESCRIPTION
**Pull request by pengyin-shan**
Fix the Navbar title for the Title 1 page (#156)

This PR will be merged directly the release PR. The development branch will be updated when merging main back to dev.

### CODE REVIEW

**Review by ywkim312 — APPROVED** [review]
Approved. Should we update changelog? Or maybe we can just ignore without updating changelog?

**Comment by sandeep-ps** [comment]
Since there is already an issue with this, I thin k it's better to include it in the CHANGELOG.

**Comment by pengyin-shan** [comment]
> Approved. Should we update changelog? Or maybe we can just ignore without updating changelog?

This is a very minor update for Title 1 page, which hasn't been released. So I think the title 1 entry should include this.

**Comment by pengyin-shan** [comment]
Ok, I just updated the changelog @ywkim312 @sandeep-ps

**Review by sandeep-ps — APPROVED** [review]

**Pull request merged**
