### PR TITLE
Prevent pages to render before all data got loaded

### PR DESCRIPTION
**Pull request by pengyin-shan**
This PR addresses issues #293 and #294:

1. Fixed the bug causing the IRA page to sometimes fail to load due to summary data arriving later than the component rendering.
2. I updated all pages on the PDL site in the same way to ensure they do not load before all necessary data is ready.
3. I cleaned up some syntax during this process to make the code more readable.

## How to Test

Open the site and check all pages. All pages should now render without any problems. Note that you may notice a slightly longer loading time for some components.

### CODE REVIEW

**Comment by navarroc** [comment]
Everything works that I tested, but it is definitely noticeably slower selecting things in the side menus. Is it worth considering just fixing the IRA page since that is the only place we saw the issue? Maybe it had something to do with the modal popup because we had never seen the issue previously.

**Comment by pengyin-shan** [comment]
> Everything works that I tested, but it is definitely noticeably slower selecting things in the side menus. Is it worth considering just fixing the IRA page since that is the only place we saw the issue? Maybe it had something to do with the modal popup because we had never seen the issue previously. It creates an odd lag when selecting a side menu button for different sub programs that feels strange.

Yes, I noticed this as well. There are two options: either take the safer approach (using this solution) or just fix IRA, but with the risk of some data not being ready on some pages, causing those pages to crash.

I'm open to hearing your thoughts. For now, I feel it is better to stand on the side of caution because during the transition to the new database, some endpoints could be unstable and cause data loading errors (we cannot predict which pages will be affected). After we finish the database migration, we can assess which pages' loading times actually affect user experience. At that point, I can add features like a progress bar to improve it. For now t's best to avoid any crashes.

**Comment by navarroc** [comment]
Thoughts @sandeep-ps, @ywkim312? My only hangup is the IRA page is the only page we've seen this issue. I understand being cautious, but we could just fix IRA and then use this fix if we find other pages have issues later. But again, we haven't seen this before on other pages. Curious what others think.

**Comment by pengyin-shan** [comment]
> Thoughts @sandeep-ps, @ywkim312? My only hangup is the IRA page is the only page we've seen this issue. I understand being cautious, but we could just fix IRA and then use this fix if we find other pages have issues later. But again, we haven't seen this before on other pages. Curious what others think.

Ah, based on what you said, one thing that just came to mind is that I can keep the branch in our repository as a backup and only update the IRA page to use this solution in the 1.0.2 release. 

If we detect that other pages have the same issue, which would indicate a broader problem, I will then reopen this PR and apply the fix to all pages. Afterward, I can address the lagging problem. Does that sound good to you?

**Comment by navarroc** [comment]
> > Thoughts @sandeep-ps, @ywkim312? My only hangup is the IRA page is the only page we've seen this issue. I understand being cautious, but we could just fix IRA and then use this fix if we find other pages have issues later. But again, we haven't seen this before on other pages. Curious what others think.
> 
> Ah, based on what you said, one thing that just came to mind is that I can keep the branch in our repository as a backup and only update the IRA page to use this solution in the 1.0.2 release.
> 
> If we detect that other pages have the same issue, which would indicate a broader problem, I will then reopen this PR and apply the fix to all pages. Afterward, I can address the lagging problem. Does that sound good to you?

I think that sounds good. We can hang on to this PR in case we need to address the issue in other pages.

**Comment by pengyin-shan** [comment]
Cool, @navarroc I'm going to close this PR. I'll msg in Slack for the new PR that targets only IRA page.

**Comment by pengyin-shan** [comment]
Close this PR as a backup for future solution

**Pull request closed without merging**
