### PR TITLE
Adjust the left menu margin, background color, and add icon

### LINKED ISSUE #61: Adjust the left menu margin and background color

### PR DESCRIPTION
**Pull request by ziyue5**
resolves #61 #62

### CODE REVIEW

**Review by navarroc — APPROVED** [review]

**Comment by sandeep-ps** [comment]
image
Does this stay on even when the left menu is closed? Also, should it rotate as the menu is open and closed? If it's not intended for this task, please let me know.

**Comment by sandeep-ps** [comment]
From looking at the design, only the selected menu item and sub-menu that opens need the background color and not the entire menu. Please see below.

image

**Review by sandeep-ps — COMMENTED** [review]
Left comments.

**Review by pengyin-shan — APPROVED** [review]
sorry i don't know the background of this PR..the code looks good to me. Just make sure your change match the design

**Comment by ziyue5** [comment]
> Left comments.

Thanks. Just fixed it.

**Comment by sandeep-ps** [comment]
Thanks. The changes look good. Approved and now merging this PR.

**Pull request merged**
