### PR TITLE
Fix the tooltip styles for semi donut chart

### LINKED ISSUE #80: Fix semi-donut chart hovering number format

### PR DESCRIPTION
**Pull request by ziyue5**
Resolves #80

### CODE REVIEW

**Comment by navarroc** [comment]
When highlighting the semi-donut, it says "payment" instead of the name of what's highlighted by the mouse. What are others opinions on this? When hovering "Structural", is it better to say:

Payment: $1,980,000

or

Structural: $1,980,000

**Comment by ziyue5** [comment]
> When highlighting the semi-donut, it says "payment" instead of the name of what's highlighted by the mouse. What are others opinions on this? When hovering "Structural", is it better to say:
> 
> Payment: $1,980,000
> 
> or
> 
> Structural: $1,980,000

No worries. I just set a new variable and was able to display text in the format like "Structural Payment: $1,980,000". Does it look better now?

**Review by pengyin-shan — COMMENTED** [review]
I tested the hover locally, and saw a blue border for the hover effect on the donut chart:

Screenshot 2023-04-12 at 4 31 20 PM

I want to confirm that this is the result we are looking for. Please feel free to move forward if so.

**Comment by ziyue5** [comment]
> I tested the hover locally, and saw a blue border for the hover effect on the donut chart:
> 
> Screenshot 2023-04-12 at 4 31 20 PM
> 
> I want to confirm that this is the result we are looking for. Please feel free to move forward if so.

Oh, I think it's a default style with recharts tooltip. Just removed it.

**Review by pengyin-shan — APPROVED** [review]
thanks @ziyue5 ! Once you finish the changes as Chris requested, feel free to merge.

**Review by navarroc — APPROVED** [review]

**Pull request merged**
